server {
    listen 80;
    server_name begreat.autorecordarchery.xyz;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    http2 on;
    server_name begreat.autorecordarchery.xyz;
    client_max_body_size 10m;

    resolver 127.0.0.11 valid=10s ipv6=off;

    ssl_certificate     /etc/nginx/ssl/begreat/fullchain.pem;
    ssl_certificate_key /etc/nginx/ssl/begreat/privkey.pem;
    include /etc/nginx/includes/ssl-params.conf;

    location ~* \.(env|bak|old|save|log|pwd|sh|yml|yaml|xml|php|asp|aspx|jsp|cgi|cfg|ini|sql|db|sqlite)$ {
        return 444;
    }
    location ~* ^/(\.aws|\.git|\.env|\.svn|phpinfo|wp-|webdav|cgi-bin|debug|composer\.json|package\.json|web\.config|crossdomain\.xml) {
        return 444;
    }

    location / {
        set $backend "begreat_app:41002";
        proxy_pass http://$backend;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection $connection_upgrade;
        proxy_read_timeout 86400s;
        access_log /var/log/nginx/begreat.ssl.access.log;
    }
}
