server {
    listen 80;
    server_name commander.autorecordarchery.xyz;
    location /.well-known/acme-challenge/ { root /var/www/certbot; }
    location / { return 301 https://$host$request_uri; }
}

server {
    listen 443 ssl;
    http2 on;
    server_name commander.autorecordarchery.xyz;
    client_max_body_size 10m;
    resolver 127.0.0.11 valid=10s ipv6=off;
    ssl_certificate /etc/nginx/ssl/commander/fullchain.pem;
    ssl_certificate_key /etc/nginx/ssl/commander/privkey.pem;
    include /etc/nginx/includes/ssl-params.conf;
    location / {
        alias /usr/share/nginx/html/commander/;
        try_files $uri $uri/ /index_fallback.html;
    }
    location = /index_fallback.html {
        internal;
        add_header Cache-Control "no-store";
        alias /usr/share/nginx/html/commander/index.html;
    }
    location = /index.html {
        add_header Cache-Control "no-store";
        alias /usr/share/nginx/html/commander/index.html;
    }
    location /api/bi/ {
        set $backend mandis_app:42002;
        proxy_pass http://$backend;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
    location /api/ {
        set $backend mandis_app:42002;
        rewrite ^/api/(.*) /$1 break;
        proxy_pass http://$backend;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
    location /begreat-admin/ {
        set $backend begreat_app:41002;
        proxy_pass http://$backend;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
    location /mandis-admin/ {
        set $backend mandis_app:42002;
        proxy_pass http://$backend;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
